sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  redis:
    host: localhost
    port: 6379
    database: 10

  wechat:
    appid: wx0a1b0afd99eb2386
    secret: 18db022b499b9df5c1b131a6c6f4de2c
#    appid: wxcd2e39f677fd30ba
#    secret: 84fbfdf5ea288f0c432d829599083637
    mchid : 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php


  location:
    shop:
      address: 江苏省镇江市京口区江苏大学
    baidu:
      ak: yawQSM1UGJ4hNyFjm73Dz2C87vA6VN2U